services:
  - type: web
    name: onlineshop-yl
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: onlineshop-db
          property: connectionString

databases:
  - name: onlineshop-db
    databaseName: onlineshop
    user: onlineshop_user